### ISSUE TITLE
Minecraft-VM stuck in "Updating" status

### ISSUE THREAD

**Issue by tommynorman** [DCtheGeek/AzureMinecraft#1]
I saw this on Channel9 and thought it was great. I created server on my Azure account and it sat at the "Updating" status for over 2 hours. I was able to remote into the server and see that the actual Windows server was up, but Minecraft was not on it yet. I delete that VM and created another one with the same result. I've seen several other videos on this that seemed to pop right up.

Am I missing something?

**Comment by DCtheGeek** [comment]
This was an error in the DSC Script for setting mcUserName on the machine.  It assumed that the provided User was a valid user in Minecraft API.  If it wasn't, it was failing and the Deployment was returning a failure.  I added a check for null response on the mcUserName and if it isn't found in the API, it doesn't try to parse or write it.  Thanks for finding this!

**Comment by tommynorman** [comment]
Thanks for the quick and thorough response, David!
